BlogPostApp/Controllers/HomeController.cs
using System.Web.Mvc;

namespace BlogPostApp.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

BlogPostApp/Controllers/ListPostController.cs
using BLL;
using BlogPostApp.ViewModel;
using BOL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace BlogPostApp.Controllers
{
    /// <summary>
    /// Controller to List,Edit,Approve,Reject Post.
    /// </summary>
    public class ListPostController : Controller
    {
        private IBlogBS blogBS;
        public ListPostController(IBlogBS _blogBS)
        {
            blogBS = _blogBS;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            var blogs = new List<Blog>();
            if(User.Identity.IsAuthenticated)
            {
                if(User.IsInRole("A"))
                {
                     blogs = blogBS.GetALL();
                }
                if (User.IsInRole("E"))
                {
                    blogs = blogBS.GetALL().Where(x => x.tbl_user.Email == User.Identity.Name).ToList();
                }
            }
            else
            {
                blogs = blogBS.GetALL().Where(x => x.StatusId == 2).ToList();
            }
            
            return View(blogs);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var blog = blogBS.GetByID(id);
            var editBlogViewModel = new EditBlogViewModel();
            editBlogViewModel.Content = blog.Content;
            editBlogViewModel.Path = blog.ImagePath;
            editBlogViewModel.Title = blog.Title;
            editBlogViewModel.BlogId = blog.BlogId;
            editBlogViewModel.ImageName = blog.ImagePath.Split('/')[blog.ImagePath.Split('/').Length - 1];
            return View(editBlogViewModel);
        }

        [HttpPost]
        public ActionResult Edit(EditBlogViewModel viewModel)
        {
            if(viewModel.Image != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(viewModel.Image.FileName);
                string extension = Path.GetExtension(viewModel.Image.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                viewModel.Path = "~/Image/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                viewModel.Image.SaveAs(fileName);
            }

            var existingBlog = blogBS.GetByID(viewModel.BlogId);
            Blog blog = new Blog();
            blog.BlogId = viewModel.BlogId;
            blog.Title = viewModel.Title;
            blog.Content = viewModel.Content;
            blog.ImagePath = viewModel.Path ?? existingBlog.ImagePath;
            blog.userId = existingBlog.userId;
            blog.Status = existingBlog.Status;
            blog.StatusId = existingBlog.StatusId;
            blogBS.Update(blog);
           return  RedirectToAction("Index");
        }

        public ActionResult Approve(int id)
        {
            var blog = blogBS.GetByID(id);
            blog.StatusId = 2;
            blogBS.Update(blog);
            TempData["Msg"] = "Blog with title:" + blog.Title + " Approved";
            return RedirectToAction("Index");
        }

        public ActionResult Reject(int id)
        {
            var blog = blogBS.GetByID(id);
            blog.StatusId = 3;
            blogBS.Update(blog);
            TempData["Msg"] = "Blog with title:" + blog.Title + " Approved";
            return RedirectToAction("Index");
        }
    }
}

BlogPostApp/Controllers/ListUserController.cs
using BLL;
using System.Web.Mvc;

namespace BlogPostApp.Controllers
{
    [Authorize(Roles = "A")]
    public class ListUserController : Controller
    {
        private IUserBS userBS;
        public ListUserController(IUserBS _userBS)
        {
            userBS = _userBS;
        }
        // GET: ListUser
        public ActionResult Index()
        {
            var users = userBS.GetALL();
            return View(users);
        }
    }
}

BlogPostApp/Controllers/LoginController.cs
using BOL;
using System;
using System.Web.Mvc;
using System.Web.Security;

namespace BlogPostApp.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult SignIn(tbl_user user)
        {
            try
            {
                if (Membership.ValidateUser(user.Email, user.Password))
                {
                    FormsAuthentication.SetAuthCookie(user.Email, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["Msg"] = "Login Failed";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception Ex)
            {
                TempData["Msg"] = "Login Failed" + Ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

BlogPostApp/Controllers/PostController.cs
using BlogPostApp.ViewModel;
using BOL;
using System;
using System.IO;
using System.Web.Mvc;
using BlogPostApp.Constants;
using BLL;
using System.Linq;

namespace BlogPostApp.Controllers
{
    /// <summary>
    /// Controller to create Post.
    /// </summary>
    public class PostController : Controller
    {
        private IUserBS userBS;
        public PostController(IUserBS _userBS)
        {
            userBS = _userBS;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(BlogViewModel blogViewModel)
        {
            string fileName = Path.GetFileNameWithoutExtension(blogViewModel.Image.FileName);
            string extension = Path.GetExtension(blogViewModel.Image.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            blogViewModel.Path = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            blogViewModel.Image.SaveAs(fileName);
            Blog blog = new Blog
            {
                Content = blogViewModel.Content,
                Title = blogViewModel.Title,
                ImagePath = blogViewModel.Path,
                StatusId = (int)BlogStatus.Draft,
                userId = userBS.GetALL().Where(x => x.Email == User.Identity.Name).FirstOrDefault().userId
            };
            using (BlogPostEntities blogPostEntities = new BlogPostEntities())
            {
                blogPostEntities.Blogs.Add(blog);
                blogPostEntities.SaveChanges();
            }
            return RedirectToAction("Index","ListPost");
        }
    }
}

BlogPostApp/Controllers/RegisterController.cs
using BLL;
using BOL;
using System;
using System.Web.Mvc;

namespace BlogPostApp.Controllers
{
    [AllowAnonymous]
    public class RegisterController : Controller
    {
        private IUserBS userBS;
        public RegisterController(IUserBS _userBS)
        {
            userBS = _userBS;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(tbl_user user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    user.Role = "E";
                    userBS.Insert(user);
                    TempData["Msg"] = "Created Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Create Failed : " + ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

BlogPostApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home</h2>
<p> This is a blog posting application.</p>

BlogPostApp/Views/ListPost/Edit.cshtml
@model BlogPostApp.ViewModel.EditBlogViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Blog</h2>


@using (Html.BeginForm("Edit", "ListPost", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="~/Image/@Model.ImageName" width="200" height="200" />
                <input type="file" name="Image" id="fileName" accept="image/x-png,image/gif,image/jpeg" onchange="validateFileType()" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <label id="ErrorLbl" class="text-danger control-label"></label>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" id="SubmitBtn" class="btn btn-default" />
            </div>
        </div>


    </div>

}


<script type="text/javascript">
    function validateFileType() {
        var fileName = document.getElementById("fileName").value;
        var fileSize = Math.round(document.getElementById("fileName").files.item(0).size / 1024);
        var idxDot = fileName.lastIndexOf(".") + 1;
        var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
        if ((extFile == "jpg" || extFile == "jpeg" || extFile == "png" || extFile == "gif") && fileSize < 5120) {
            document.getElementById("SubmitBtn").disabled = false;
            document.getElementById("ErrorLbl").innerHTML = "";
        } else {
            document.getElementById("SubmitBtn").disabled = true;
            document.getElementById("ErrorLbl").innerHTML = "Only jpg/jpeg,png and gif files are allowed!";
        }
    }
</script>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BlogPostApp/Views/ListPost/Index.cshtml
@model IEnumerable<BOL.Blog>

@{
    ViewBag.Title = "Index";
}

@if (TempData["Msg"] != null)
{
    <div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @TempData["Msg"].ToString()
    </div>
}

<h2>Blogs</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status.StatusName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.StatusName)
            </td>
            <td>
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.BlogId })
                    if (User.IsInRole("A"))
                    {
                        @Html.ActionLink(" | Approve | ", "Approve", new { id = item.BlogId }) 
                        @Html.ActionLink("Reject", "Reject", new { id = item.BlogId })
                    }
                }

            </td>
        </tr>
    }
</table>

BlogPostApp/Views/ListUser/Index.cshtml
@model IEnumerable<BOL.tbl_user>

@{
    ViewBag.Title = "Index";
}

<h2>Users</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Role)
        </td>
    </tr>
}

</table>

BlogPostApp/Views/Login/Index.cshtml
@model BOL.tbl_user

@{
    ViewBag.Title = "Index";
}

@if (TempData["Msg"] != null)
{
    <div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @TempData["Msg"].ToString()
    </div>
}

<h2>Sign In</h2>

@using (Html.BeginForm("SignIn", "Login", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SignIn" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BlogPostApp/Views/Post/Index.cshtml
@model BlogPostApp.ViewModel.BlogViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Post Blog</h2>


@using (Html.BeginForm("Create", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="fileName" name="Image" accept="image/x-png,image/gif,image/jpeg" onchange="validateFileType()" required />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <label id="ErrorLbl" class="text-danger control-label"></label>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit Post" id="SubmitBtn" class="btn btn-default" />
        </div>
    </div>
</div>
}

<script type="text/javascript">
    function validateFileType() {
        var fileName = document.getElementById("fileName").value;
        var fileSize = Math.round(document.getElementById("fileName").files.item(0).size / 1024);
        var idxDot = fileName.lastIndexOf(".") + 1;
        var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
        if ((extFile == "jpg" || extFile == "jpeg" || extFile == "png" || extFile == "gif") && fileSize < 5120) {
            document.getElementById("SubmitBtn").disabled = false;
            document.getElementById("ErrorLbl").innerHTML = "";
        } else {
            document.getElementById("SubmitBtn").disabled = true;
            document.getElementById("ErrorLbl").innerHTML = "Only jpg/jpeg,png and gif files are allowed!";
        }
    }
</script>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BlogPostApp/Views/Register/Index.cshtml
@model BOL.tbl_user

@{
    ViewBag.Title = "Index";
}

<h2>User Registration</h2>
@if (TempData["Msg"] != null)
{<div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @TempData["Msg"].ToString()
    </div>}

@using (Html.BeginForm("Create", "Register", FormMethod.Post))
{
    @Html.AntiForgeryToken()

 <div class="form-horizontal">
     <hr />
     @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     <div class="form-group">
         @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
             @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
             @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
         </div>
     </div>

     <div class="form-group">
         @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
             @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
             @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
         </div>
     </div>

     <div class="form-group">
         @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
             @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
             @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
         </div>
     </div>


     <div class="form-group">
         <div class="col-md-offset-2 col-md-10">
             <input type="submit" value="Create" class="btn btn-default" />
         </div>
     </div>
 </div>
}

BlogPostApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Blogs", "Index", "ListPost", new { area = "" }, new { @class = "navbar-brand" })</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("A"))
                        {
                            <li>@Html.ActionLink("Users", "Index", "ListUser", new { area = "" }, new { @class = "navbar-brand" })</li>
                        }
                        <li>@Html.ActionLink("PostBlog", "Index", "Post", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("SignOut", "SignOut", "Login", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li><a href="#">Welcome Mr/Ms @User.Identity.Name.ToString() </a></li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Register", "Index", "Register", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("LogIn", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })</li>
                    }

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>